name: pasarlele_loka
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+3

  bloc: ^4.0.0
  flutter_bloc: ^4.0.0

  flutter_svg: ^0.17.4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/btn_google_light_normal_ios.svg
